#spring.application.name=Restful_api_assignments
spring.application.name=JPA_3_ASSIGNMENT


#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=aryan
#spring.datasource.password=aryan
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


spring.datasource.url=jdbc:mysql://localhost:3306/my_db
spring.datasource.username=root
spring.datasource.password=19082003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true